baseURL = "https://wesleyjrz.com"
title = "Wesley Jr++"
theme = "risotto"
copyright = "Copyright © 2022-current • Wesley Vieira Santos Jr."
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = false

enableRobotsTXT = true

# Enable relativeURLs if your site hosted on GitHub.io
relativeURLs = false

# Google Analytics
# googleAnalytics = "UA-123-45"

ignoreErrors = ["error-remote-getjson"]

sectionPagesMenu = "main"

[markup.goldmark.renderer]
unsafe = true # enable raw HTML in Markdown

[params]
noindex = false
ipv6ready = false

[params.theme]
palette = "windows-95"

[params.about]
title = "Wesley Jr."
description = "An eclectic free software devotee and his journey through knowledge."
logo_image = "https://avatars.githubusercontent.com/u/60184588?v=4" # use my GitHub profile picture

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/wesleyjrz"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:dev@wesleyjrz.com"

[menu]

	[[menu.main]]
		identifier = "books"
		name = "Books"
		url = "/book-rec"

	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about"
