baseURL = "https://wesleyjrz.com/"
title = "Wesley Jr++"
theme = "hugo-notepadium"
copyright = "Copyright © 2022-current • Wesley Vieira Santos Jr."

languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = false

enableRobotsTXT = true

# [services.googleAnalytics]
# id = '' # Google tag ID

[markup.goldmark.renderer]
unsafe = true # enable raw HTML in Markdown

[markup.highlight]
codeFences = true
noClasses = false

[params]
style = "auto"
logo = "/static/logo.png"
slogan = "Free as in freedom"
license = "CC BY 4.0"
ipv6ready = false

[params.profile]
enable = true
avatar = "https://avatars.githubusercontent.com/u/60184588?v=4"
name = "Wesley V. Santos Jr."
bio = "An eclectic mind. Free software enthusiast."
twitter = "wesleyjrz"
github = "wesleyjrz"
email = "dev@wesleyjrz.com"

[params.nav]
showCategories = true
showTags = true

[params.syntax]
use = "none"
theme = "xcode"
darkTheme = "xcode-dark"

[params.math]
enable = true
use = "katex"

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Books"
url = "/books"

[caches]
	[caches.images]
		dir = ':cacheDir/images'
