baseURL = "https://wesleyjrz.com"
title = "Wesley Jr++"
theme = "hugo-notepadium"
copyright = "Copyright &copy 2022-current • Wesley V. Santos Jr."

languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = false

enableRobotsTXT = true

# Enable relativeURLs if your site hosted on GitHub.io
relativeURLs = false

# Enable Disqus
# disqusShortname = "XXX"

# Google Analytics
# googleAnalytics = "UA-123-45"

ignoreErrors = ["error-remote-getjson"]

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true # enable raw HTML in Markdown

[params]
style = "dark" # light, dark, auto
dateFormat = "Jan 02, 2006" # if unset, default is "2006-01-02"
readingTime = true # show reading time after article date
logo = "logo.png"
slogan = "I use NixOS btw."
ipv6ready = false

[params.comments]
enable = false # enable/disable comments globally

[params.comments.utterances]
# repo = "MetalBlueberry/MetalBlueberry.github.io" # enable comments with [utteranc.es](https://utteranc.es/)

[params.math]
enable = false # load math globally
use = "katex" # builtin: "katex", "mathjax"

[params.syntax]
use = "none" # builtin: "prismjs", "hljs". "none" means Chroma
theme = "github"
darkTheme = "github-dark"

[params.share]
enable = false # enable/disable share globally
# addThisId = ""
# inlineToolId = ""

[params.profile]
	enable = true
	avatar = "https://avatars.githubusercontent.com/u/60184588?v=4" # use my GitHub profile picture
	name = "Wesley Jr."
	bio = "Born self-taught, eclectic, future computer engineer, GNU/Linux devotee and open-source software supporter." # support markdown syntax
	github = "wesleyjrz"
	# docker = ""
	# twitter = "wesleyjrz"
	email = "wesleyjr2002@gmail.com"

[params.nav]
showCategories = true # /categories/
showTags = false # /tags/

[[params.nav.custom]]
title = "Book rec."
url = "/book-rec"

# [[params.nav.custom]]
# title = "About"
# url = "/about"
